export type ConfidenceCategory = 'High' | 'Moderate' | 'Low';
export type Contribution = {
  feature: string; feature_value: number; contribution: number;
  direction: 'increases_model_bust_score' | 'decreases_model_bust_score' | 'neutral';
};
export type GridCell = {
  initialization_time: string; valid_time: string; lead_day: number; latitude: number; longitude: number;
  forecast_precipitation: number; forecast_temperature_2m: number;
  forecast_relative_humidity_2m: number; forecast_mean_sea_level_pressure: number;
  forecast_u_wind_10m: number; forecast_v_wind_10m: number; forecast_wind_speed_10m: number;
  precipitation_gradient_mm_per_degree: number; bust_probability: number; confidence_score: number;
  confidence_category: ConfidenceCategory; is_bust_predicted: boolean; decision_threshold: number;
  explanations: Contribution[]; explanation_summary: string; explanation_base_value: number;
  expected_absolute_error_mm?: number; gefs_precipitation_mean_mm?: number;
  gefs_end_window_spread_6h_mm?: number; forecast_precipitable_water?: number;
  forecast_cape_surface?: number;
};
export type RiskLocation = { latitude: number; longitude: number; lead_day: number; bust_probability: number };
export type DaySummary = {
  lead_day: number; number_of_predictions: number; mean_bust_probability: number;
  maximum_bust_probability: number; mean_confidence: number; percentage_predicted_bust: number;
  highest_risk_location: RiskLocation; hotspot_count: number;
};
export type OverallSummary = Omit<DaySummary, 'lead_day'> & { lead_day_count: number; grid_cell_count: number };
export type Health = { api_ready: boolean; model_ready: boolean; forecast_ready: boolean;
  status: 'ready' | 'not_ready'; model_id: string | null; decision_threshold: number | null;
  features: string[]; available_initializations: string[]; cached_initializations: number;
  source_kind?: 'historical_demo' | 'forecast_only_feed' | 'current_forecast' | 'mixed'; source_label?: string; state_count?: number;
  primary_initialization?: string | null;
  run_metadata?: Record<string, { run_kind: 'historical_demo' | 'current_forecast' | 'forecast_only_feed'; label: string;
    initialization_utc: string; valid_start_utc?: string; valid_end_utc?: string; model_id?: string; run_id?: string }>;
  current_warning?: string | null;
  grid: { south: number; north: number; west: number; east: number;
    latitude_step_degrees: number | null; longitude_step_degrees: number | null } | null };
export type StateInfo = { name: string; grid_cell_count: number; has_grid_centers: boolean };
export type StatesResponse = { boundary_source: string; grid_resolution_degrees: number; states: StateInfo[] };
export type StateDay = { state: string; lead_day: number; grid_cell_count: number; coverage: string;
  mean_forecast_confidence: number; mean_bust_probability: number; predicted_bust_cell_percentage: number;
  mean_expected_absolute_error_mm: number; mean_gefs_end_window_spread_6h_mm: number;
  highest_risk_cell: GridCell; hotspot_count: number };
export type StateSummaryResponse = { state: string; initialization_time: string; grid_cell_count: number;
  coverage: string; most_uncertain_lead_day: number; days: StateDay[] };
export type EscalationResponse = { initialization_time: string; lead_day: number; previous_initialization: string;
  emerging_bust_cells: number; resolved_bust_cells: number; new_hotspot_regions: number;
  provenance: string };
export type SummaryResponse = { initialization_time: string; model_id: string | null;
  decision_threshold: number; initialization_summary: OverallSummary; lead_day_summaries: DaySummary[] };
export type DayResponse = { initialization_time: string; lead_day: number; records: GridCell[] };
export type BoundingBox = { south: number; north: number; west: number; east: number };
export type Hotspot = { hotspot_id: string; lead_day: number; number_of_cells: number;
  centroid_latitude: number; centroid_longitude: number; mean_bust_probability: number;
  max_bust_probability: number; mean_confidence: number; bounding_box: BoundingBox;
  member_cells: { latitude: number; longitude: number }[] };
export type HotspotsResponse = { initialization_time: string; lead_day: number; hotspots: Hotspot[] };
export type TimelinePoint = Pick<DaySummary, 'lead_day' | 'mean_bust_probability' |
  'maximum_bust_probability' | 'mean_confidence' | 'percentage_predicted_bust' | 'hotspot_count'>;
export type TimelineResponse = { initialization_time: string; days: TimelinePoint[] };

export type ComparisonCell = { latitude: number; longitude: number; lead_day: number;
  previous_bust_probability: number; current_bust_probability: number; delta_bust_probability: number;
  previous_confidence: number; current_confidence: number; delta_confidence: number;
  state: 'emerging' | 'resolved' | 'persistent' | 'neither' };
export type Comparison = { current_initialization: string; previous_initialization: string; lead_day: number;
  number_of_cells: number; mean_probability_delta: number; mean_confidence_delta: number;
  emerging_bust_cells: number; resolved_bust_cells: number; persistent_bust_cells: number;
  previous_hotspot_count: number; current_hotspot_count: number; hotspot_count_delta: number;
  new_hotspot_regions: number; resolved_hotspot_regions: number;
  largest_risk_increases: ComparisonCell[]; largest_risk_decreases: ComparisonCell[];
  cells: ComparisonCell[] };
export type Analog = { initialization_time: string; lead_day: number; latitude: number; longitude: number;
  similarity_score: number; distance: number; forecast_precipitation: number;
  reference_precipitation: number; absolute_error: number; is_bust: boolean };
export type AnalogsResponse = { initialization_time: string; latitude: number; longitude: number; lead_day: number;
  number_of_analogs: number; percentage_busted: number | null; mean_historical_absolute_error: number | null;
  analogs: Analog[]; provenance: string };
export type BriefResponse = { initialization_time: string; lead_day: number; confidence_category: ConfidenceCategory;
  mean_confidence: number; mean_bust_probability: number; hotspot_count: number;
  highest_risk_location: RiskLocation; contributing_features: string[]; text: string;
  caveat: string };
export type VariableTrendResponse = { initialization_time: string; field: string;
  days: { lead_day: number; value: number }[] };
